name: Test Action
on:
  push:
    path-ignore:
    - README.md
    - LICENSE
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      uses: ./
      with:
        file: tests/run-tests.wl
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
