on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      uses: ./
      with:
        script: tests/run-tests.wl
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASSWORD: ${{ secrets.WolframPW }}
