name: Test Action
on:
  push:
    paths-ignore:
    - README.md
    - LICENSE
  schedule:
  - cron: 0 0 1 * *
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      uses: ./
      with:
        file: tests/run-tests.wl
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    - name: Test arguments
      uses: ./
      with:
        file: tests/args-test.wl
        args: 1 var=2
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: System Benchmark
      uses: ./
      with:
        file: tests/benchmark.wl
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
